### ISSUE TITLE
[Fluff] Add Social Media Preview Image to repository

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#163]
If you go to Settings > Options > Social Preview, there's an option to add a social media preview image to the repository.

![image](https://user-images.githubusercontent.com/1100550/92513642-7e6ac800-f1c5-11ea-8a99-e85251133ac1.png)

I think it would be neat to add one for this repo.

**Comment by NarryG** [comment]
Sounds like a fun little thing. Might try whipping something together.

**Comment by NarryG** [comment]
![RTC Logo + Text](https://user-images.githubusercontent.com/3047793/92654679-2e236100-f2be-11ea-9d7e-68ca25f413aa.png)
Done
