### ISSUE TITLE
[CI] CemuStub build task is returning false positive results

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#195]
Recently, some pull requests made it through CI that broke the CemuStub build.

**Comment by NarryG** [comment]
```
Project "D:\a\RTCV\RTCV\CemuStub-Vanguard\CemuStub-Vanguard.sln" on node 1 (default targets). 

12ValidateSolutionConfiguration: 

13 Building solution configuration "Debug|Any CPU". 

14ValidateProjects: 

15 The project "CemuStub" is not selected for building in solution configuration "Debug|Any CPU". 

16Project "D:\a\RTCV\RTCV\CemuStub-Vanguard\CemuStub-Vanguard.sln" (1) is building "D:\a\RTCV\RTCV\RTCV\Source\Frontend\StandaloneRTC\StandaloneRTC.csproj" (2) on node 1 (default targets).

```

**Comment by scowalt** [comment]
Per the Discord chat, there are two solutions:

1. Use a different configuration in the `RTCV` CI (we'll likely want to fix `CemuStub-Vanguard`'s CI too)
2. Modify `CemuStub-Vanguard` so that the `"Debug|Any CPU"` configuration is valid

**Comment by NarryG** [comment]
I'm leaning on #2 as for all our projects, debug should build fine. I'm going to take a look at it just in case CemuStub was set to x64 for some reason (we hook the cemu window but that should still be fine from AnyCpu on a 64 bit system)

**Comment by NarryG** [comment]
Resolved via https://github.com/redscientistlabs/CemuStub-Vanguard/commit/e64b1a59c3cd85d3a5838df3050d3d33753dabe0
