### ISSUE TITLE
[Feature] User analytics / telemetry

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#216]
Could potentially be useful to setup some infrastructure to better understand the scope of the RTC's userbase and how people are using the tooling.

**Comment by NarryG** [comment]
I'd rather not have any form of tracking within the application itself as I don't want to deal with the data, but I wouldn't be opposed to better download stats.

**Comment by scowalt** [comment]
Ah, great point. I forgot to consider that. I'll close this then since this is more of a site issue than an RTCV issue
