### ISSUE TITLE
Broken logic in BlastTools.GenerateBlastLayersFromBlastGeneratorProtos

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#226]
https://github.com/redscientistlabs/RTCV/blob/506/Source/Libraries/CorruptCore/BlastTools.cs#L216

```
        internal static List<BlastGeneratorProto> GenerateBlastLayersFromBlastGeneratorProtos(List<BlastGeneratorProto> blastLayers)
        {
            foreach (BlastGeneratorProto bgp in blastLayers)
            {
                //Only generate if there's no BlastLayer.
                //A new proto is always generated if the cell is dirty which means no BlastLayer will exist
                //Otherwise, we just return the existing BlastLayer
                if (true || bgp != null && bgp.bl == null)
                {
                    Console.Write("BGP was dirty. Generating BlastLayer\n");
                    bgp.bl = bgp.GenerateBlastLayer();
                }
            }
            return blastLayers;
        }
```

Right now `(true || bgp != null && bgp.bl == null)` is always going to return `true`, so the `BlastLayer` will always be assigned. I'm not 100% sure what the intention is here.

**Comment by NarryG** [comment]
Can you git blame and find the commit? I can figure out if I was testing something and I accidentally left it in or what.

**Comment by scowalt** [comment]
e5b2d69e84c9978628492244e7f721784f26890a

**Comment by NarryG** [comment]
I'm _guessing_ I stuck `true ||` there to test the other changes but I want to verify this. I'll look at it.

**Comment by NarryG** [comment]
Resolved. It was a leftover from testing. https://github.com/redscientistlabs/RTCV/commit/e94f0350ec661b4d306c04db3d6cbcbfb6fbc729
