### ISSUE TITLE
Stockpile.Name is an unused field

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#241]
Currently throws a compiler warning that I'm working on suppressing.

We should investigate removing this member if it's not used, but doing so now may break serialization.

**Comment by NarryG** [comment]
I'm fairly sure we can change these to properties without issue with json.net, we just need to double check.

**Comment by NarryG** [comment]
I should really read the message first before replying.

With the default json.net behavior, it should be possible to remove this without issues if it's unused.

**Comment by scowalt** [comment]
Fixed with #261
