### ISSUE TITLE
Fix dolphin's dedpendency on the StandaloneRTC project

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#243]
The StandaloneRTC project really shouldn't be included in the SLNs of the other projects so if it's included in Dolphin and preventing it from building without the RuntimeIdentifiers, we should remove that.  

_Originally posted by @NarryG in https://github.com/redscientistlabs/RTCV/pull/239#discussion_r491750370_

**Comment by NarryG** [comment]
Resolved
https://github.com/redscientistlabs/dolphin-vanguard/commit/03022bc0b0639520ab0744a076ed641fa18951f4
https://github.com/redscientistlabs/dolphin-vanguard/commit/4256ae5664e17f04f6b97ba5e3d382f42715c75b
