### ISSUE TITLE
Investigate Ceras and CompilerServices.Unsafe dependency conflict

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#244]
I'm honestly not sure. I may fork Ceras to resolve the CompilerServices.Unsafe conflict (it wasn't a complicated issue if memory serves me well). Not sure about the Reflection.Metadata conflict as I don't actually know what's using that.

_Originally posted by @NarryG in https://github.com/redscientistlabs/RTCV/pull/239#discussion_r491750415_

**Comment by NarryG** [comment]
I poked at this a bit and it seems like whatever issue I was previously having may be gone. I still need to test more but I brought everything up to the latest version and didn't appear to get any errors with my quick test

**Comment by NarryG** [comment]
Closed with https://github.com/redscientistlabs/RTCV/commit/e46acba8e36f1227bbf1dd494531d3c541f0eb0e
