### ISSUE TITLE
Is there/will there be a way to compile to and/or install for linux?

### ISSUE THREAD

**Issue by itstoast27** [redscientistlabs/RTCV#252]
I do not own a windows computer, and would like to get the action on my Chromebook (with debian bullseye). I would just like to know if anyone knows of/has made a version working on a debian-based linux version, and if there is any official version (regarding the application). Any replies to this are greatly appreciated.

**Comment by NarryG** [comment]
We're pretty hard-locked to Windows for a variety of reasons.   
- UI is Winforms (mono is pretty crusty,)
- Bizhawk doesn't have proper Linux support (they're working on it but it's crusty)
- All the C++ emulators are glued to the RTC code using C++/CLI, a Windows-specific extension to the C++ standard (reverse P/invoke would not be portable without extra work anyways).  

So for the forseeable future, unless someone were to take on the task to completely replace the C++/CLI infrastructure with a reverse P/Invoke infrastructure, and someone were to go through the mountains of work of getting things running under Mono, Windows is the only supported platform.

**Comment by itstoast27** [comment]
any news?

**Comment by ircluzar** [comment]
hi, the current roadmap for linux is to progressively refactor rtc to
decouple corruptcore and uicore. this will (over time) make the transition
to dotnet6 and eventually linux to be more feasible (right now it's not
really possible with dotnet framework and the way internals currently are)

I'd say, we might unfortunately be years from a fully linux compatible
build. until then you could use a vm or wine or crossover to try getting it
to work on other oses than windows but zero guarantees for wine or
crossover. it might just not work at all.

if you can make a windows vm on linux kvm and enable gpu pass-through, that
would be your best option right now for a machine that has linux as the
host os.

cheers

**Comment by itstoast27** [comment]
thank you for the response :> glad that it's loosely on the way, but i guess ill try and get a vm set up on my system soon.
