### ISSUE TITLE
The RTC Launcher fails to extract the RTCV archive on ubuntu 20.04 with mono

### ISSUE THREAD

**Issue by Derailedzack** [redscientistlabs/RTCV#345]
The Launcher doesn't fully download the archive and fails to extract it.

**Comment by NarryG** [comment]
None of the RTC-supported emulator forks are supported under Linux on Mono. We currently have no plans to support Linux under Mono, so for now this is a won't-fix. Apologies, but we're just currently unable to support Linux.

**Comment by Derailedzack** [comment]
Also I have started porting the filestub to C++

**Comment by NarryG** [comment]
Feel free! I'd love to see it when it's done. Was the intention to connect to the RTC or just act as a standalone corruptor? FileStub in the end is only a stub for the RTC, and is dependent on all the RTC code.

**Comment by Derailedzack** [comment]
I could make the file stub a shared lib.

**Comment by Derailedzack** [comment]
It would be standalone.

**Comment by ircluzar** [comment]
once of our discord members proved that most of RTCV's programs can run on Linux using lutris and winetricks. While we don't officially support it, we did put their documentation on the wiki so if you want to check it out, you might save yourself a few headaches.
https://corrupt.wiki/corruptors/rtc/running-rtcv-on-linux
