### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by dmj-games** [redscientistlabs/RTCV#382]
I would like RTC to be ported to linux if the emulators have a linux release
would really love to!

**Comment by NarryG** [comment]
Eventually we'd love to see this happen (see https://github.com/redscientistlabs/RTCV/issues/252) but the developer support just isn't there. There's a lot of code that needs to be reworked and nobody is really dedicated to it. For right now, Linux is a "maybe eventually but don't count on it" unless someone comes and decides they want to work the port-job themselves.
