### ISSUE TITLE
System can't find FileStub.exe?

### ISSUE THREAD

**Issue by oof-hie** [redscientistlabs/RTCV#448]
![RTC Launcher 2022  10  25  8_50_44](https://user-images.githubusercontent.com/74454909/197702633-762ce4bb-9e5b-473f-9fb3-9218e4375c16.png)

(bottom line is "system can't find the file" wich is filestub.exe)

**Comment by ircluzar** [comment]
Your antivirus probably deleted the file for some reason. Delete FileStub and reinstall it. If this happens again, try disabling your AV temporarily or whitelisting the file. For more technical support, come talk to us on our discord.
